# Generated by Django 2.1.5 on 2019-01-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longtitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_lon', models.DecimalField(decimal_places=2, max_digits=5)),
                ('depart_lat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dest_lon', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dest_lat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taker_score', models.IntegerField(null=True)),
                ('rider_score', models.IntegerField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('arrival_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
